name: affect12_en
anchors:
- id: joy
  surface: joy
  language: en
- id: sadness
  surface: sadness
  language: en
- id: fear
  surface: fear
  language: en
- id: anger
  surface: anger
  language: en
- id: calmness
  surface: calmness
  language: en
- id: excitement
  surface: excitement
  language: en
- id: pleasure
  surface: pleasure
  language: en
- id: discomfort
  surface: discomfort
  language: en
- id: confidence
  surface: confidence
  language: en
- id: helplessness
  surface: helplessness
  language: en
- id: interest
  surface: interest
  language: en
- id: boredom
  surface: boredom
  language: en
